apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v2
spec:
  replicas: 1
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: omerurhan/kubia:v2
        name: nodejs