apiVersion: v1
kind: Pod
metadata:
  name: pod-limits-to-high
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    resources:
      limits:
        cpu: 1001m
        memory: 10Mi