apiVersion: v1
kind: Pod
metadata:
  name: requests-pod-unallocable
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    name: main
    resources:
      limits:
        cpu: 9
        memory: 10Mi