kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  image: kindest/node:v1.25.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30900
    hostPort: 30900
    protocol: TCP
- role: worker
  image: kindest/node:v1.25.0
- role: worker
  image: kindest/node:v1.25.0