apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kubia
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 2
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubia

